FROM eclipse-temurin:17-jdk AS builder

WORKDIR /photon
RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/komoot/photon.git .
RUN chmod +x gradlew && ./gradlew build -x test

FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=builder /photon/target/photon-*.jar /app/photon.jar

EXPOSE 2322

ENTRYPOINT ["java", "-jar", "photon.jar"]
